version: "2"
services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - config:/config
      - media_movies:/data/movies
      - media_tvshows:/data/tvshows
      - transcode:/transcode
    ports:
      - 8096:8096
    restart: unless-stopped

volumes:
    config:
        driver: local
    transcode:
        driver: local
    media_movies:
        external: true
    media_tvshows:
        external: true
